### ISSUE TITLE
Create "Get Random Article" use case

### ISSUE THREAD

**Issue by tjcaul** [NewsPeek/NewsPeek#14]
Should be the most basic. Gets an article from the API (API should just do mock data at this point by #11 ), censors it, then displays it. The biggest question is: where in our CLEAN architecture are the censorship rules getting applied to the file??

**Comment by tjcaul** [comment]
ChatGPT tells me censorship should be a helper class: `use_case/CensorshipService.java`. Maybe it can have a method ```CensoredArticle censor(Article article, CensorshipRuleSet ruleset);```

Even better, we can have an interface `CensorshipService` and an implementation 

```
class ScanningCensorshipService implements CensorshipService {
  @Override
  CensoredArticle censor(Article article, CensorshipRuleSet ruleset) {
    // loop through the words in the article.getText() and apply censorship rules
  }
}
```

**Comment by tjcaul** [comment]
The getting of the article doesn't need to be actually random; we just need to call the `APIDataAccessObject` like `api.getRandomArticle()` or something.

**Comment by tjcaul** [comment]
I wrote it, but we still need a button to trigger it and a view to display the results.

**Comment by 1lizard** [comment]
thank you tyson
